# Generated by Django 4.1.7 on 2023-02-22 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('Name', models.CharField(max_length=60)),
                ('InsertUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InsertedRecords', to=settings.AUTH_USER_MODEL)),
                ('LastUpdateUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UpdatedRecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
