# Generated by Django 4.1.7 on 2023-02-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('OriginalName', models.CharField(max_length=100)),
                ('NameEN', models.CharField(blank=True, max_length=100, null=True)),
                ('NamePT_BR', models.CharField(blank=True, max_length=100, null=True)),
                ('ReleaseYear', models.IntegerField(blank=True, null=True)),
                ('RunTime', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='artwork_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=60)),
                ('NamePT_BR', models.CharField(max_length=60)),
                ('Flag', models.ImageField(blank=True, null=True, upload_to='countries_flags')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'types of artwork',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now_add=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(auto_now=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=60)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('DateOfDeath', models.DateField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='person_photos')),
                ('CountryOfBirth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artwork')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='Distributors',
            field=models.ManyToManyField(to='core.distributor'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='Genres',
            field=models.ManyToManyField(to='core.genre'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='Members',
            field=models.ManyToManyField(through='core.Membership', to='core.person'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='OriginalLanguage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.language'),
        ),
    ]
