# Generated by Django 4.1.7 on 2023-02-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField()),
                ('NameEN', models.CharField(max_length=60)),
                ('NamePT_BR', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='InsertUser',
        ),
        migrations.RemoveField(
            model_name='person',
            name='LastUpdateUser',
        ),
        migrations.AddField(
            model_name='person',
            name='InsertUserId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='LastUpdateUserId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
