# Generated by Django 4.1.7 on 2023-02-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
