# Generated by Django 4.1.7 on 2023-02-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_remove_person_insertuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='LastUpdateUserId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastUpdateUserId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
