# Generated by Django 4.1.7 on 2023-02-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_options_alter_country_lastupdateuserid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='Flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
