# Generated by Django 4.1.7 on 2023-02-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='country',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='country',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='language',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='language',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='person',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='person',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='role',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='role',
            name='LastUpdateUserId',
        ),
        migrations.RemoveField(
            model_name='typeofartwork',
            name='InsertUserId',
        ),
        migrations.RemoveField(
            model_name='typeofartwork',
            name='LastUpdateUserId',
        ),
    ]
