# Generated by Django 4.1.7 on 2023-03-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_insertuserid_artwork_insertuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Flag',
            field=models.ImageField(blank=True, null=True, upload_to='countries_flags/'),
        ),
    ]
