# Generated by Django 4.1.7 on 2023-02-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('NameEN', models.CharField(max_length=30)),
                ('NamePT_BR', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
