# Generated by Django 4.1.7 on 2023-03-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_typeofartwork_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='OriginalName',
            new_name='OriginalTitle',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='NameEN',
            new_name='TitleEN',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='NamePT_BR',
            new_name='TitlePT_BR',
        ),
    ]
