# Generated by Django 4.1.7 on 2023-02-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_distributor_genre_language_typeofartwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofartwork',
            options={'verbose_name_plural': 'types of artwork'},
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='NameEN',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='NamePT_BR',
        ),
    ]
