# Generated by Django 4.1.7 on 2023-02-23 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_typeofartwork_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeOfInsert', models.DateTimeField(auto_now=True)),
                ('DateTimeOfLastUpdate', models.DateTimeField(blank=True, null=True)),
                ('InsertUserId', models.IntegerField()),
                ('LastUpdateUserId', models.IntegerField(blank=True, null=True)),
                ('OriginalName', models.CharField(max_length=100)),
                ('NameEN', models.CharField(blank=True, max_length=100, null=True)),
                ('NamePT_BR', models.CharField(blank=True, max_length=100, null=True)),
                ('ReleaseYear', models.IntegerField(blank=True, null=True)),
                ('RunTime', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='artwork_photos')),
                ('OriginalLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
