# Generated by Django 4.1.7 on 2023-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='Genres',
            field=models.ManyToManyField(blank=True, null=True, to='core.genre'),
        ),
    ]
