# Generated by Django 4.1.7 on 2023-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_artwork_distributors_alter_artwork_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='Genres',
            field=models.ManyToManyField(blank=True, null=True, to='core.genre'),
        ),
    ]
