# Generated by Django 4.1.7 on 2023-02-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_artwork_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='Distributors',
            field=models.ManyToManyField(blank=True, null=True, to='core.distributor'),
        ),
    ]
