# Generated by Django 4.1.7 on 2023-02-24 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_artwork_distributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artwork')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='Members',
            field=models.ManyToManyField(blank=True, null=True, through='core.Membership', to='core.person'),
        ),
    ]
