# Generated by Django 4.1.7 on 2023-03-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_artwork_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CountryOfBirth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.country'),
        ),
    ]
