# Generated by Django 4.1.7 on 2023-03-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profiles'},
        ),
    ]
