# Generated by Django 4.1.7 on 2023-03-10 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_country_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='TypeOfArtwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.typeofartwork'),
        ),
    ]
