# Generated by Django 4.1.7 on 2023-03-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_artwork_typeofartwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='TypeOfArtwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.typeofartwork'),
            preserve_default=False,
        ),
    ]
